runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /
    static_files: ass2/index.html
    upload: ass2/index.html

  - url: /(.*)
    static_files: ass2/\1
    upload: ass2/(.*)
